[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://spa-booking-system-vqmo.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/booking"
  to = "/booking.html"
  status = 200

[[redirects]]
  from = "/book"
  to = "/booking.html"
  status = 200